name: story_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-213.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_fonts: ^6.2.0
  http: ^1.2.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  ionicons: ^0.2.2
  shared_preferences: ^2.2.2
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
